### ISSUE TITLE
Group EC2 idle and untagged machines by tags

### ISSUE THREAD

**Issue by ashishkamra** [redhat-performance/cloud-governance#208]
When identifying untagged and idle EC2 instances, it will be good to also retrieve the tags on those instance (whatever tags are available) and try to do some intelligent grouping based on that. For eg. All EC2 instances of an openshift cluster will have a key with the following format
kubernetes.io/cluster/<cluster-name>-xxxxx

It will be useful to group machines with the same tag when visualizing the results in Kibana.

**Comment by ebattat** [comment]
Adding the cluster name for ec2 policies
