### ISSUE TITLE
Add auto email for alert results

### ISSUE THREAD

**Issue by ebattat** [redhat-performance/cloud-governance#337]
Send an auto mail to owner of the alerts.
1. Fetch the alert owner
2. Create this step in Jenkins pipeline
3. Send email to the alert owner and cc Cloud manager with dedicate detail.
4. Need to improve to find the resource owner through AWS cloud-trail.

**Comment by athiruma** [comment]
Already implemented this feature.
[Code Link](https://github.com/redhat-performance/cloud-governance/blob/main/cloud_governance/common/mails/postfix.py)
