### ISSUE TITLE
Stop and Alert on wasted running instances

### ISSUE THREAD

**Issue by ashishkamra** [redhat-performance/cloud-governance#479]
**Is your feature request related to a problem? Please describe.**
Users forget to terminate or shutdown their cloud resources when they are not using them. This leads to waste and adds to our operational expense.

**Describe the solution you'd like**
1. In the excel sheet that is maintained for user tags, every user should mention ranges for working hours in UTC. Like 10 AM - 4 PM, 8 PM - 10 PM. Something like that. The accounts used for CI runs can mention the full 24 hours as the working hours.
2. For all resources found running outside the working hours, an alert email should be sent to the user.
3. The user somehow needs to confirm in **real time** that the resource is still being used. This is TBD. 
4. If the user does not confirm within 30 mins of receiving the alert, another warning email should be sent with the manager and a team mailing list in cc. 
5. If the user or the manager or some other team member does not confirm within 30 mins of the warning email, the resource should be terminated. An email should be sent post termination explaining why the resource was terminated.

**Describe alternatives you've considered**
There is no alternative. We rely on manual monitoring, and users being responsible. Mistakes happen all the time.

**Additional context**
None

**Comment by ashishkamra** [comment]
cc @dagrayvid wdyt ?

**Comment by dagrayvid** [comment]
That makes sense to me, for things that are not marked as long running.

Is the information in the spreadsheet currently detailed enough for cloud governance to know which clusters are "marked as long running"? If not, we will need that functionality. For instance, maybe we need a way for users to say clusters named "foo-bar-*" are intentionally long running, or something like that.

**Comment by ashishkamra** [comment]
The spreadsheet currently only has user accounts and tags. I agree it should be extended with names/tags of long running resources that the automation should not worry about. Having said that, marking something as long running can not be a way out of cloud-governance monitoring. We should have an some kind of approval process before marking resources as long running.

**Comment by ebattat** [comment]
@ashishkamra, great feature.
We can fetch the user timezone directly from ldap, so no need to fill it in spreadsheet.
I think that the working hours should be 8:00-20:00, and in outside working hour we can stop the machine and send email notification user/manager that after 24 hours it terminated.
For ec2 that should run 24/7, need to add the tag "policy:skip".
wdyt ?

**Comment by dagrayvid** [comment]
+1 to stopping the instance for 24 hrs before terminating

**Comment by ashishkamra** [comment]
I might have over complicated the solution. Here is another proposal:
For every cluster/resource spun up, users must include either one of the following tags
1) Short running expiration date/time: Can not be more than 24 hours beyond the resource creation time
2) long running expiration date/time: resources intended to be continuously up for more than 24 hours are assumed to be long running. Can not be more than 72 hours beyond the resource creation time.

Cloud governance automation will stop instances found in violation of the above policy and send alert email to the user. There is no need to terminate instances as stopped instances do not incur cost (only EBS cost).

For long running resources beyond 72 hours, line manager approval is required before launching such resources and the following tag should be included for such resources.
Extra long running approved by: {manager name who approved it}

This proposal should have buy in from stakeholders as it will be disruptive to the regular workflow.

**Comment by dagrayvid** [comment]
Ideally we could make 24 hours the default so that users don't need to manually add a tag unless they need a resource for more than 24 hours.

**Comment by ashishkamra** [comment]
That is even better. 24 hours default. 72 hours max (indicated in a tag). Beyond that, get manager approval (also indicated in a tag).

**Comment by smalleni** [comment]
> I might have over complicated the solution. Here is another proposal: For every cluster/resource spun up, users must include either one of the following tags
How do we enforce this user tagging? What if no tag exists?
> 
> 1. Short running expiration date/time: Can not be more than 24 hours beyond the resource creation time
> 2. long running expiration date/time: resources intended to be continuously up for more than 24 hours are assumed to be long running. Can not be more than 72 hours beyond the resource creation time.
> 
> Cloud governance automation will stop instances found in violation of the above policy and send alert email to the user. There is no need to terminate instances as stopped instances do not incur cost (only EBS cost).
> 
> For long running resources beyond 72 hours, line manager approval is required before launching such resources and the following tag should be included for such resources. Extra long running approved by: {manager name who approved it}
> 
> This proposal should have buy in from stakeholders as it will be disruptive to the regular workflow.

**Comment by ebattat** [comment]
@smalleni,
So If I understand clear we have 3 run type:
1. Short run - 24 hours   
2. Long run - <= 72 hours
3. Permanent run - > 72 hours

The policies should be:
1. Short run - stop it after 24 hours, no special tag needed.
2. Long run - User need to add tag **run_type: long**, Do we need any special approval for it ?
3. Permanent run - run_type: permanent, need manager approval for it, Maybe Manager can sign on it in a dedicate spreadsheet and we skip those resource only if it in this list. Only Manager will have permission for it.  

Do you think this approach is good enough ?

**Comment by ashishkamra** [comment]
> Permanent run - run_type: permanent, need manager approval for it, Maybe Manager can sign on it in a dedicate spreadsheet and we skip those resource only if it in this list. Only Manager will have permission for it.

My suggestion is to take approval offline through any means from any manager (not just the line manager) and just note the approval with another tag "Approved by".

**Comment by ebattat** [comment]
Hi @ashishkamra, @athiruma, @natashba 
I have summarized here what we decided in cloud-governance meeting:

The are only 2 run types: (no need 24 hours type)

```
1. Short run - **72 hours**, stop it after 72 hours, no special tag needed.
2. Long run (Project) - need manager approval and add 2 tags: 
    -      duration: X weeks
    -      manager_approval: manager_name

```

The flow should be:
1. User open Jira ticket and add his Manager [Project: Cloud-Governance ]
2. Add Project details: Number of Instances, type, duration, Cost estimation.
3. Manager should approve it.
4. User can created the instance and **must** add 2 tags: **duration and manager_approval** and update the instance id in Jira.
5. Cloud governance fetch data from Jira and upload it to ElasticSearch.
6. Approved data displayed in Grafana panel.
7. Cloud governance send email notification a week before the duration is over. 
8. Cloud governance stop project instances if duration is over and no extend.

Please let me know that you are OK with the flow.
cc: @smalleni

**Comment by ebattat** [comment]
Finally we have implemented CRO [Cloud Resource Orchestration] feature for controlling cost optimization and saving per user.
For more details see [PR](https://github.com/redhat-performance/cloud-governance/pull/585)
