### ISSUE TITLE
[zombie_cluster_resource]: Include Deletion of OIDC/IAM Roles & Users

### ISSUE THREAD

**Issue by krishvoor** [redhat-performance/cloud-governance#675]
**Is your feature request related to a problem? Please describe.**
OIDC/ IAM Roles and users are not getting cleaned/deleted, after associated cluster resources are cleaned-up during
[zombie_cluster_resources deletion](https://github.com/redhat-performance/cloud-governance/blob/main/cloud_governance/policy/aws/zombie_cluster_resource.py 
)

**Describe the solution you'd like**
Extend the current functionality to include clean-up of OIDC/IAM Roles as well.

**Describe alternatives you've considered**
Can include an AWS Lambda-based OIDC/IAM pruner, allowing us to be efficient, however this might a very little cost associated.

**Additional context**
Slack thread: https://redhat-internal.slack.com/archives/C01SNQ4Q1B8/p1695750940444179

**Comment by venkataanil** [comment]
Our CI is frequently failing as we are exceeding the roles limit. Please enhance zombie resource script to cleanup any stale roles.

**Comment by athiruma** [comment]
Created the Lambda pruner to delete the unused roles.
