### ISSUE TITLE
Idle RDS instances

### ISSUE THREAD

**Issue by rccrdpccl** [redhat-performance/cloud-governance#774]
**Is your feature request related to a problem? Please describe.**
We would like to detect and act on idle AWS RDS instances

**Describe the solution you'd like**
When we detect idle AWS RDS instances, we would like to delete them

**Additional context**
One way to detect idle RDS instances is through `DatabaseConnections` Cloudwatch Metric.
It appears to detect even very short lived connections, as long as we connect to a specific database (which is normally the case).
However, it will only appear with small enough period: in my test of 3s connection, it has been detected as `minimum(DatabaseConnections)` for periods  1m and lower.
The greater the period, the longer the connection would need to be.
In my experience, most of the use cases will have long lived connections, but there might be some cases where short lived connections are used (i.e. cron executing short read and/or write operations)

**Comment by athiruma** [comment]
Refer to PR # [780](https://github.com/redhat-performance/cloud-governance/pull/780)
