### ISSUE TITLE
Python 3.11/3.12 support

### ISSUE THREAD

**Issue by ebattat** [redhat-performance/cloud-governance#776]
**Is your feature request related to a problem? Please describe.**
Currently CG support up to Python 3.10
**Describe the solution you'd like**
Need to add support for Python 3.11/3.12, specially in unittest and integration 
**Describe alternatives you've considered**

**Additional context**

**Comment by athiruma** [comment]
Refer to PR# [794](https://github.com/redhat-performance/cloud-governance/pull/794)
